name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - name: Check for known vulnerabilities
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
        with:
          go-version-file: go.mod
          go-package: ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Test
        run: go test ./...
      - name: Build
        run: go build ./...

  generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Check protobuf generation
        run: ./scripts/check-generated.sh

  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false
      - name: Test against NeoShowcase
        run: ./scripts/test-integration.sh
